- .vscode/settings.json
- src/components/Select/index.stories.mdx
- src/components/Select/index.tsx
- src/components/TreeSelect/index.less
- src/components/TreeSelect/index.stories.mdx
- src/components/TreeSelect/index.tsx
https://app.asana.com/0/887895452935610/1172153979111069/f
> Added TreeSelect make async loading and pagination for Select

- .antd-tools.config.js
- .gitignore
- .gulp/getBabelCommonConfig.js
- .gulp/getTSCommonConfig.js
- .gulp/postcssConfig.js
- .gulp/projectHelper.js
- .gulp/replaceLib.js
- .gulp/transformLess.js
- gulpfile.js
- package.json
- rollup.config.js
- src/index.tsx
https://app.asana.com/0/887895452935610/1172934083826695/f
> Setup build with gulp

- src/components/TableSelectColumnsModal/index.tsx
https://app.asana.com/0/887895452935610/1193387646043915
> Fix: all children columns are selected if one of them checked.

- src/components/Table/hooks/useColumns.tsx
- src/components/Table/index.less
https://app.asana.com/0/887895452935610/1194838594007809
> Fix: parent columns are not displayed if some of the children selected.

- src/components/TableTransposeButton/index.tsx
https://app.asana.com/0/1193634516986442/1195744800106311
> reset table search on rotation

- src/components/TableSelectColumnsModal/index.tsx
- src/components/TreeSearch/index.tsx
- src/utils/data/tree.ts
https://app.asana.com/0/887895452935610/1198173520291887
> TreeSearch component logic modified.

- src/components/DrawerSelect/index.less
https://app.asana.com/0/887895452935610/1198886098019299
> fix: set min-width for checkbox

- src/components/PeriodSelect/constants.ts
- src/components/PeriodSelect/helper.ts
- src/components/PeriodSelect/index.less
- src/components/PeriodSelect/index.stories.mdx
- src/components/PeriodSelect/index.tsx
https://app.asana.com/0/1193634516986442/1198916955137390
> Sprint 23 period picker

- src/components/Table/hooks/useColumns.tsx
https://app.asana.com/0/887895452935610/1199206643933909
> Fix default filtered value of table th.

- src/components/TransferTable/index.tsx
https://app.asana.com/0/888249068922589/1199679332563341/f
> TransferTable filter refactoring.

- src/components/TransferTable/index.less
https://app.asana.com/0/1193634516986442/1199689190538686
> fix mobile version

- src/components/FormBuilder/fields/DatePicker.tsx
- src/components/FormBuilder/types.ts
https://app.asana.com/0/1193634516986442/1199640092500336
> add optional prop inputReadOnly

- src/components/Table/reducer.test.ts
- src/components/Table/reducer.ts
https://app.asana.com/0/1199654129021413/1199986433259827
> Fix table pagination.

- src/components/DrawerSelect/index.tsx
https://app.asana.com/0/1199654129021413/1200035785346470
> make filterOption  editable for select

- setupTests.ts
- src/components/AppLoader/index.less
- src/components/AppLoader/index.tsx
- src/utils/theme.ts
https://app.asana.com/0/1199654129021413/1200041363352260
> add dark theme for AppLoader

- src/components/DrawerTreeSelect/__snapshots__/index.test.tsx.snap
- src/components/DrawerTreeSelect/index.less
- src/components/DrawerTreeSelect/index.tsx
https://app.asana.com/0/1199654129021413/1200078527873778
> fix tag when select all

- src/components/Table/components/Column.tsx
- src/components/Table/index.less
- src/components/Table/index.tsx
- src/components/Table/types.ts
https://app.asana.com/0/1199654129021413/1200010627211400
> add onColumnWidthChange event

- src/components/Table/components/Column.tsx
- src/components/Table/types.ts
https://app.asana.com/0/1199654129021413/1200010627211400
> fix resize issue

- src/components/Table/index.less
https://app.asana.com/0/1199654129021413/1200016286791482
> fix min-width for filtered column

- src/components/Table/index.less
- src/components/Table/index.tsx
- src/components/Table/types.ts
https://app.asana.com/0/1199654129021413/1200016286791482
> Sprint 10 auto col width

- src/components/BarTable/__snapshots__/index.test.tsx.snap
- src/components/Table/index.less
- src/components/Table/index.tsx
- src/components/Table/rtl.less
- src/components/Table/types.ts
https://app.asana.com/0/1199654129021413/1200129657448932
> add compressColumn prop & update snap

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/TransferFilter/List/ListBody.tsx
- src/components/TransferFilter/List/index.tsx
- src/components/TransferFilter/helper.ts
https://app.asana.com/0/1199654129021413/1200079416751528
> update transfer search

- src/components/TransferFilter/List/index.tsx
https://app.asana.com/0/1199654129021413/1200155989857815
> update select all

- src/components/PeriodSelect/index.tsx
- src/components/PeriodSelect/types.ts
https://app.asana.com/0/1199654129021413/1200084433685820
https://app.asana.com/0/1199654129021413/1200124267458157
> allow select future period & add date presets

- src/components/DateRangePicker/index.tsx
- src/components/DateRangePicker/types.d.ts
- src/components/FormBuilder/fields/DateRangePicker.tsx
- src/components/PeriodSelect/index.tsx
https://app.asana.com/0/1199654129021413/1200084433685820
> Sprint 11 update date picker

- src/components/PeriodSelect/usePeriodSelect.ts
https://app.asana.com/0/1199654129021413/1200173909704733
> update available periods when set custom data

- src/components/TableTransposeButton/index.tsx
https://app.asana.com/0/0/1200244128402093/f
> fix rotation with unselected columns

- src/components/BarTable/__snapshots__/index.test.tsx.snap
- src/components/PeriodSelect/helper.ts
- src/components/Table/__snapshots__/index.test.tsx.snap
https://app.asana.com/0/1199654129021413/1200188230476929
> Fix prev. ranges in PeriodSelect.

- src/components/DrawerTreeSelect/index.tsx
https://app.asana.com/0/1199654129021413/1200244073546318
> select leaf elements instead of root

- src/components/DrawerTreeSelect/index.tsx
- src/components/DrawerTreeSelect/types.ts
- src/components/DrawerTreeSelect/utils/valueUtil.ts
- src/components/FormBuilder/types.ts
- src/utils/data/tree.ts
https://app.asana.com/0/1199654129021413/1199935217584891
> Shop markers

- src/components/DrawerSelect/index.tsx
https://app.asana.com/0/1199654129021413/1200314560052167
> fix DrawerSelect selected items on search

- src/components/FormBuilder/fields/DrawerTreeSelect.tsx
- src/components/FormBuilder/types.ts
https://app.asana.com/0/1199654129021413/1200340473356233
> Add forceOnChange prop to FieldDrawerTreeSelect.

- src/components/DateRangePicker/index.tsx
https://app.asana.com/0/1141335112847483/1200390155180987/f
> remove time from date

- src/components/Help/components/Menu/index.tsx
- src/components/Help/index.tsx
https://app.asana.com/0/1193634516986442/1200358269379311
> add tour menu

- src/components/Table/index.less
https://app.asana.com/0/1199654129021413/1200421423917697
> Fix nested table columns width.

- src/components/TransferFilter/index.less
- src/components/TransferFilter/index.tsx
https://app.asana.com/0/888249068922589/1200419728445870/f
> Hide check all btn if the tree is collapsed (TransferFilter).

- src/components/Select/index.tsx
- src/components/Select/types.ts
https://app.asana.com/0/1199654129021413/1200434052606208
> update Select loadData

- src/components/TableTemplates/index.less
https://app.asana.com/0/1175088311467015/1200439556520907
> fix toolbar align

- src/components/Help/components/SupportModal/index.tsx
- src/components/HighChart/index.tsx
https://app.asana.com/0/1199654129021413/1200467062362865
> Fix labels in Support modal.

- src/components/Table/types.ts
- src/components/TableXlsxExporter/exporters.ts
https://app.asana.com/0/888249068922589/1200471505239171/f
> replace null to empty obj

- src/components/Table/types.ts
- src/components/TableXlsxExporter/exporters.ts
https://app.asana.com/0/1193634516986442/1200451957443235
> add aditional sheet

- src/components/ColorPicker/index.less
https://app.asana.com/0/1199654129021413/1200483705497120
> Fix input color on ColorPicker.

- src/components/FormBuilder/fields/Password.tsx
https://app.asana.com/0/1199654129021413/1200540949308172
> Fix password field.

- src/components/DrawerTreeSelect/index.tsx
https://app.asana.com/0/1199654129021413/1200515023865704
> Fix all checkbox logic (DrawerTreeSelect).

- src/components/Drawer/index.less
- src/components/Help/components/Menu/index.tsx
- src/components/Help/index.less
- src/components/List/index.less
- src/components/Table/index.less
- src/styles/dark-variables.less
- src/styles/variables.less
https://app.asana.com/0/883840802957506/1200489366387891/f
> add new button and update styles

- src/components/Help/components/Menu/index.tsx
- src/components/Help/index.less
https://app.asana.com/0/883840802957506/1200489366387891/f
> fix size and padding

- src/components/Table/utils/utils.ts
https://app.asana.com/0/1193634516986442/1200657353147741
> fix xlsx export on empty cell

- src/components/Table/components/Column.tsx
- src/components/Table/index.less
https://app.asana.com/0/1193634516986442/1200439333817214
> Sprint 18 safari column resize

- src/components/DrawerSelect/index.tsx
https://app.asana.com/0/888249068922589/1200712367165416/f
> fix delete tag

- src/components/DrawerTreeSelect/index.tsx
- src/components/DrawerTreeSelect/types.ts
- src/components/FormBuilder/fields/DrawerTreeSelect.tsx
- src/components/FormBuilder/types.ts
- src/hooks/useDeepEqualMemo.ts
https://app.asana.com/0/1199654129021413/1200630782235040
> Depend metrics

- src/components/DrawerSelect/index.tsx
- src/components/FormBuilder/fields/DrawerSelect.tsx
- src/components/FormBuilder/types.ts
https://app.asana.com/0/1161358880059181/1200459444362989/f
> add checking if selected count biggest than needed

- src/components/Help/components/Menu/index.tsx
- src/components/Help/index.tsx
https://app.asana.com/0/883840802957506/1200485026873925/f
> add onVisibleChange to help menu dropdown

- src/components/DrawerSelect/index.tsx
https://app.asana.com/0/0/1200747853809775/f
> fix when newValue return undefined

- src/components/Table/utils/utils.ts
https://app.asana.com/0/1199654129021413/1200692045582013/f
> set column between columns

- src/components/FormBuilder/types.ts
- src/components/Select/index.tsx
https://app.asana.com/0/888249068922589/1200800580516052/f
> add disabled property

- src/components/TimeRangePicker/index.less
- src/components/TimeRangePicker/index.tsx
https://app.asana.com/0/1199654129021413/1200904732556314
> remove useless dropdown shadow

- src/components/FormBuilder/fields/DateRangePicker.tsx
https://app.asana.com/0/1146826576266818/1200987426581834
> Fix daterangepicker props (from, to) if value is of type Array.

- src/components/TransferTable/index.tsx
https://app.asana.com/0/1199654129021413/1200860462743999
> add config for transfer table

- src/components/TransferFilter/List/ListBody.tsx
- src/components/TransferFilter/List/ListTree.tsx
- src/components/TransferFilter/List/index.tsx
- src/components/TransferFilter/types.ts
- src/components/Tree/index.tsx
- src/components/TreeSearch/index.tsx
https://app.asana.com/0/1199654129021413/1201026037603129
> Make items in tree selectable.

- src/components/TableSelectColumnsModal/index.less
- src/components/TreeSearch/index.tsx
https://app.asana.com/0/1146826576266818/1201086359680728
> Disable groups if search mode is enabled (table columns).

- src/components/DrawerTreeSelect/Markers.tsx
- src/components/DrawerTreeSelect/__snapshots__/index.test.tsx.snap
- src/components/DrawerTreeSelect/index.less
- src/components/DrawerTreeSelect/index.tsx
- src/components/DrawerTreeSelect/types.ts
- src/components/FormBuilder/fields/DrawerTreeSelect.tsx
- src/components/FormBuilder/types.ts
https://app.asana.com/0/1199654129021413/1201083863971283
> Add Markers component (DrawerTreeSelect).

- src/components/TableTemplates/index.tsx
https://app.asana.com/0/1146826576266818/1201263064892530
> Fix logic of table templates.

- src/components/FormBuilder/fields/DrawerTreeSelect.tsx
- src/components/FormBuilder/types.ts
https://app.asana.com/0/1199654129021413/1201344998063012
> add treeNodeFilterProp for FieldDrawerTreeSelect

- src/components/TableTemplates/components/Dropdown.tsx
- src/components/TableTemplates/components/Template.tsx
- src/components/TableTemplates/index.less
- src/components/TableTemplates/index.tsx
https://app.asana.com/0/1199654129021413/1201379323825467/f
> change icon, reset selected, bold font to selected

- src/components/Help/components/Menu/index.tsx
- src/components/Help/index.tsx
https://app.asana.com/0/1199654129021413/1201426129629390
> control Help menu visible

- src/components/Table/components/Column.tsx
- src/components/TableTemplates/index.tsx
- src/components/TimeRangePicker/__snapshots__/index.test.tsx.snap
https://app.asana.com/0/1199654129021413/1200677494055682
> save columns width to table templates

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/reducer.ts
- src/components/Table/types.ts
- src/components/TableMenu/__snapshots__/index.test.tsx.snap
- src/components/TableMenu/index.test.tsx
- src/components/TableMenu/index.tsx
- src/components/TableTemplates/index.tsx
https://app.asana.com/0/1199654129021413/1201505279914194/f
> Sprint 30 save fixed total to templates

- src/components/TableMenu/index.tsx
https://app.asana.com/0/888249068922589/1201532867257485/f
> add check is tableContext exist

- src/components/Table/hooks/useDataSource.ts
- src/components/Table/types.ts
- src/components/Table/utils/handlers.ts
https://app.asana.com/0/1199654129021413/1201473360509989
--------------------
ІМПАКТ
--------------------
Сервіс: BI New
Звіти:
- Продажі товарів (розподіл ABC, ABC по категоріях)
- Товари на виведення
Змінено: приховані колонки на таблиці не будуть відображатися в результатах пошуку
> Exclude hidden columns from search.

- src/components/ErrorBoundary/index.less
- src/components/ErrorBoundary/index.tsx
https://app.asana.com/0/888249068922589/1201524719986754/f
> import styles to component

- src/components/Table/components/Column.tsx
https://app.asana.com/0/888249068922589/1201544553791203/f
> fix columns auto  growing each second

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/components/Column.tsx
- src/components/Table/reducer.ts
- src/components/Table/types.ts
- src/components/TableTemplates/index.tsx
https://app.asana.com/0/1199654129021413/1201586873476616
> fix template select

- src/components/Table/reducer.ts
https://app.asana.com/0/888249068922589/1201586709125427/f
> clean parent map

- src/utils/calendar/index.ts
https://app.asana.com/0/888249068922589/1201637289393173/f
> add default calendar params

- src/components/Table/utils/handlers.ts
https://app.asana.com/0/1201607547880049/1201663203508228
> fix table internal search when columns unselected

- src/components/DateRangePicker/index.tsx
- src/components/DateRangePicker/types.ts
- src/components/FormBuilder/fields/DateRangePicker.tsx
https://app.asana.com/0/1201607547880049/1201691598024334
> Fix maxDate for presets if period is unlimited (promos).

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/reducer.ts
- src/components/TableTemplates/index.tsx
https://app.asana.com/0/1201607547880049/1201714377258239
> Set fixedTotal to TRUE by default.

- src/components/DrawerSelect/index.tsx
- src/components/FormBuilder/types.ts
https://app.asana.com/0/1201607547880049/1201714078445101
> add abillity to show confirm modal before select

- src/components/FormBuilder/validators/TextValidator.ts
https://app.asana.com/0/1146826576266818/1201707452368658
> Add TextValidator.

- src/components/DrawerTreeSelect/index.tsx
- src/components/TableMenu/__snapshots__/index.test.tsx.snap
https://app.asana.com/0/1201607547880049/1201721386844647
> fix thee select dependent items

- src/components/Table/components/VList/Wrapper.tsx
https://app.asana.com/0/888249068922589/1201805319812632/f
> fix virtual table wrapper

- src/components/TransferFilter/List/__snapshots__/index.test.tsx.snap
- src/components/TransferFilter/List/index.test.tsx
- src/components/TransferFilter/List/index.tsx
- src/components/TransferFilter/__snapshots__/index.test.tsx.snap
https://app.asana.com/0/1146826576266818/1201671136190042
> Fix logic of All checkbox (TransferFilter).

- src/components/TableSelectColumnsModal/Modal.tsx
https://app.asana.com/0/1201607547880049/1201872239391817
> Fix max col. count.

- src/components/DrawerTreeSelect/index.less
https://app.asana.com/0/1201607547880049/1201892756551738
> Fix tree select scroll bar (disable auto-hidden behaviour).

- src/styles/scrollbar.less
https://app.asana.com/0/1201607547880049/1201892756551738
> Move scrollbar styles to RC.

- src/components/TransferFilter/List/index.tsx
https://app.asana.com/0/888249068922589/1201939687034432/f
> Fix all checkbox (TransferFilter).

- src/components/TableSelectColumnsModal/Modal.tsx
- src/components/TableSelectColumnsModal/index.tsx
https://app.asana.com/0/1201607547880049/1201961438182632
> Add hiddenColumns param (TableSelectColumnsModal).

- src/components/DrawerSelect/index.tsx
- src/components/DrawerTreeSelect/index.tsx
- src/components/DrawerTreeSelect/types.ts
- src/components/FormBuilder/types.ts
https://app.asana.com/0/1201607547880049/1201544570701337
> Add maxTagLength prop.

- src/components/PhoneInput/index.tsx
https://app.clickup.com/t/2ya7vvt
> Fix PhoneInput.

- src/components/DrawerTreeSelect/antd/RcSelect.tsx
https://app.clickup.com/t/24430889/BES-22664
> Fix listHeight in DrawerTreeSelect after window resize.

- src/components/TableSelectColumnsModal/Modal.tsx
https://app.clickup.com/t/24430889/BES-17
> Unhighlight table columns button upon apply or cancel.

- src/components/DrawerSelect/index.tsx
https://app.clickup.com/t/24430889/BES-23354
> Display id if label is empty (DrawerSelect).

- src/components/TransferFilter/List/index.tsx
https://app.clickup.com/t/24430889/BES-23651
> fix zero page

- src/components/DrawerSelect/index.tsx
- src/components/FormBuilder/fields/DrawerSelect.tsx
- src/components/FormBuilder/types.ts
- src/components/PeriodSelect/__snapshots__/index.test.tsx.snap
- src/components/PeriodSelect/index.test.tsx
https://app.clickup.com/t/24430889/BES-10518
> Add noticeRender & hideSearch params (DrawerSelect).

- src/utils/fiscalCalendar/index.ts
https://app.clickup.com/t/24430889/BES-23661
> Fix startDate (financial calendar).

- src/components/Table/__snapshots__/index.test.tsx.snap
- src/components/Table/components/Cell.tsx
- src/components/Table/components/Column.tsx
- src/components/Table/hooks/useColumns.tsx
- src/components/TableMenu/__snapshots__/index.test.tsx.snap
https://app.clickup.com/t/24430889/BES-24117
> Change table columns width.

- src/components/Table/index.tsx
https://app.clickup.com/t/24430889/BES-23691
> Add expandRow() method.
